backend:
  replicaCount: 4
  resources:
    limits:
      cpu: 400m
      memory: 384Mi
    requests:
      cpu: 150m
      memory: 192Mi

frontend:
  replicaCount: 4
  resources:
    limits:
      cpu: 400m
      memory: 384Mi
    requests:
      cpu: 150m
      memory: 192Mi
