apiVersion: v1
kind: Service
metadata:
  labels:
    app: lunar-app
  name: lunar-app-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: lunar-app
  type: NodePort