apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apollo-app
  name: apollo-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: apollo-app
  template:
    metadata:
      labels:
        app: apollo-app
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: apollo-app
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports: 
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
