apiVersion: v1
kind: Service
metadata:
  labels:
    app: apollo-app
  name: apollo-app-service
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: apollo-app
  type: {{ .Values.service.type }}
